import "./globals.css";
import { AuthProvider } from "./provider";
import { Roboto } from "next/font/google";
// import Navbar from "@/components/layout/Navbar";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700"],
  subsets: ["latin"],
})

export const metadata = {
  title: "Kratos",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className}`}
      >
        <AuthProvider>
          {/* <Navbar /> */}
          <main>{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
